# Generated by Django 3.0.5 on 2020-04-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.URLField(max_length=6)),
                ('long', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', editable=False, max_length=12)),
                ('agent', models.CharField(default='', editable=False, max_length=200)),
                ('amount', models.IntegerField(default=1)),
                ('link', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='url_shortener_app.url')),
            ],
        ),
    ]
