# Generated by Django 3.0.5 on 2020-04-13 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_url_shortener_code_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_shortener_code',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url_shortener_code',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url_shortener_code',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url_shortener_code',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
