# Generated by Django 3.0.5 on 2020-04-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_auto_20200401_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='text',
            new_name='item_text',
        ),
    ]
